package parser

import (
	"regexp"
	"strconv"
	"strings"
)

var highlightRangeRegex = regexp.MustCompile(`\{([0-9\s,-]+)\}`)

// parseCodeInfo parses language and highlight line ranges from fenced code block info.
// Examples:
//   "go" -> "go", nil
//   "go {2,4-6}" -> "go", [][2]int{{2, 2}, {4, 6}}
//   "python { 1-3, 5 }" -> "python", [][2]int{{1, 3}, {5, 5}}
func parseCodeInfo(info string) (string, [][2]int) {
	info = strings.TrimSpace(info)
	if info == "" {
		return "", nil
	}

	loc := highlightRangeRegex.FindStringSubmatchIndex(info)
	if loc == nil || len(loc) < 4 {
		parts := strings.Fields(info)
		if len(parts) > 0 {
			return parts[0], nil
		}
		return "", nil
	}

	rangeStr := info[loc[2]:loc[3]]
	lang := strings.TrimSpace(info[:loc[0]])
	if fields := strings.Fields(lang); len(fields) > 0 {
		lang = fields[0]
	}

	ranges := parseHighlightRanges(rangeStr)
	return lang, ranges
}

func parseHighlightRanges(s string) [][2]int {
	parts := strings.Split(s, ",")
	var ranges [][2]int

	for _, part := range parts {
		part = strings.TrimSpace(part)
		if part == "" {
			continue
		}

		if dashIdx := strings.Index(part, "-"); dashIdx != -1 {
			startStr := strings.TrimSpace(part[:dashIdx])
			endStr := strings.TrimSpace(part[dashIdx+1:])
			start, err1 := strconv.Atoi(startStr)
			end, err2 := strconv.Atoi(endStr)
			if err1 == nil && err2 == nil && start > 0 && end >= start {
				ranges = append(ranges, [2]int{start, end})
			}
		} else {
			line, err := strconv.Atoi(part)
			if err == nil && line > 0 {
				ranges = append(ranges, [2]int{line, line})
			}
		}
	}

	return ranges
}

// postProcessHighlightedCode adds CSS classes to pre and line elements generated by Chroma.
func postProcessHighlightedCode(html string, hasHighlights bool) string {
	if !hasHighlights {
		if strings.Contains(html, "<pre class=\"") {
			return strings.Replace(html, "<pre class=\"", `<pre class="highlight-container `, 1)
		} else if strings.HasPrefix(html, "<pre") {
			return strings.Replace(html, "<pre", `<pre class="highlight-container"`, 1)
		}
		return html
	}

	// For code with highlights:
	// 1. Add class="highlight-container has-highlights" to <pre>
	if strings.Contains(html, "<pre class=\"") {
		html = strings.Replace(html, "<pre class=\"", `<pre class="highlight-container has-highlights `, 1)
	} else if strings.HasPrefix(html, "<pre") {
		html = strings.Replace(html, "<pre", `<pre class="highlight-container has-highlights"`, 1)
	}

	// 2. Mark highlighted lines with class="line hl"
	html = strings.ReplaceAll(html, `<span style="display:flex; background-color:`, `<span class="line hl" style="display:flex; background-color:`)

	// 3. Mark standard lines with class="line"
	html = strings.ReplaceAll(html, `<span style="display:flex;">`, `<span class="line" style="display:flex;">`)

	return html
}

